# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Docker Image (Nightly)

on:
  schedule:
    - cron: '0 10 * * *' # everyday at 10am

jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v4

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      -
        name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            blacktop/ghidra
            ghcr.io/${{ github.repository }}

      -
        name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image (Nightly)
        id: docker_build_nightly
        uses: docker/build-push-action@v4
        with:
          context: ./nightly
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            blacktop/ghidra:10-nightly
            blacktop/ghidra:nightly
            ghcr.io/blacktop/ghidra:10-nightly
            ghcr.io/blacktop/ghidra:nightly
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
