# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Docker Image

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'
  # pull_request:
  #   branches:
  #     - 'master'

jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v4

      -
        name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            blacktop/ghidra
            ghcr.io/${{ github.repository }}

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      -
        name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Build and push Docker image (v9)
      #   id: docker_build_9
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: ./9
      #     push: ${{ github.event_name != 'pull_request' }}
      #     tags: |
      #       blacktop/ghidra:9
      #       blacktop/ghidra:9.2
      #       blacktop/ghidra:9.2.4
      #     platforms: linux/amd64 # No native binaries or binary build script included
      #     labels: ${{ steps.meta.outputs.labels }}

      # - name: Build and push Docker image (v10)
      #   id: docker_build_10
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: ./10
      #     push: ${{ github.event_name != 'pull_request' }}
      #     tags: |
      #       blacktop/ghidra:10
      #       blacktop/ghidra:10.4
      #       blacktop/ghidra:10.4.0
      #       ghcr.io/blacktop/ghidra:10
      #       ghcr.io/blacktop/ghidra:10.4
      #       ghcr.io/blacktop/ghidra:10.4.0
      #     platforms: linux/amd64,linux/arm64
      #     labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push Docker image (v11)
        id: docker_build_11
        uses: docker/build-push-action@v6
        with:
          context: ./11
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            blacktop/ghidra:11
            blacktop/ghidra:11.3
            blacktop/ghidra:11.3.1
            blacktop/ghidra:latest
            ghcr.io/blacktop/ghidra:11
            ghcr.io/blacktop/ghidra:11.3
            ghcr.io/blacktop/ghidra:11.3.1
            ghcr.io/blacktop/ghidra:latest
          platforms: linux/amd64,linux/arm64
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push Docker image (alpine)
        id: docker_build_alpine
        uses: docker/build-push-action@v6
        with:
          context: ./alpine
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            blacktop/ghidra:11-alpine
            blacktop/ghidra:11.3-alpine
            blacktop/ghidra:11.3.1-alpine
            blacktop/ghidra:alpine
            ghcr.io/blacktop/ghidra:11-alpine
            ghcr.io/blacktop/ghidra:11.3-alpine
            ghcr.io/blacktop/ghidra:11.3.1-alpine
            ghcr.io/blacktop/ghidra:alpine
          platforms: linux/amd64,linux/arm64
          labels: ${{ steps.meta.outputs.labels }}
